version: '3'

services:
  cpplint_src:
    build: docker/cpplint
    command: bash -c "find src/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
    volumes:
      - .:/app/

  cpplint_test:
    build: docker/cpplint
    command: bash -c "find unit_tests/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
    volumes:
      - .:/app/

  unit_tests:
    build: .
    command: reduct_tests

  api_tests:
    build: api_tests
    environment:
      STORAGE_HOST: reduct_storage
    depends_on:
      - reduct_storage

  reduct_storage:
    build: .
