name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check code in /src
        run: docker-compose run cpplint_src
      - name: Check code in /test
        run: docker-compose run cpplint_test

  build_and_test:
    needs: cpplint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build code in Docker
        run: docker-compose build

  unit_test:
    needs: cpplint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose run unit_tests


  api_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Storage
        run: docker-compose up -d reduct_storage
      - name: Run API tests
        run: docker-compose run api_tests
      - name: Down Storage
        run: docker-compose down
        if: always()