name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check code in /src
        run: docker-compose run cpplint_src
      - name: Check code in /test
        run: docker-compose run cpplint_test

  build_and_push:
    runs-on: ubuntu-latest
    needs: cpplint
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{github.repository}}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar


  unit_test:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a

      - name: Run tests
        run: docker run -rm ghcr.io/${{github.repository}} reduct_tests
#
#  api_test:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#    steps:
#      - uses: actions/checkout@v2
#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Run Storage
#        run: docker run --rm -p 8383:8383 -d ghcr.io/${{github.repository}}
#      - name: Build API tests
#        run: docker build -t api_tests ./api_tests
#      - name: Run API tests
#        run: docker run --rm apt_tests